language: cpp
sudo: true
dist: trusty

compiler:
    - g++

#Build steps
before_install:
    - sudo apt-get install libsdl-mixer1.2-dev libsdl-image1.2-dev libsdl-ttf2.0-dev libopenal-dev libglm-dev -y

script: make LINUX=1